# Generated by Django 4.2.5 on 2023-09-13 14:07

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('hash', models.CharField(max_length=20, unique=True)),
                ('COEFFICIENTS', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='123', max_length=20)),
                ('birth_date', models.DateField(max_length=30)),
                ('ERN', models.FloatField()),
                ('ENN', models.FloatField()),
                ('ESN', models.FloatField()),
                ('speciality', models.CharField(default='PC', max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(related_name='app_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='app_users_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('admitted_students', models.ManyToManyField(to='Main.student')),
                ('university', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Main.university')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_courses_hashes', models.CharField(max_length=300)),
                ('admitted_in_choice', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.university')),
            ],
        ),
    ]
