# Generated by Django 4.2.5 on 2023-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
