# Generated by Django 4.2.5 on 2023-09-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_university_admission_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='confirmed_students',
            field=models.ManyToManyField(related_name='confirmed', to='Main.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='upgrading_students',
            field=models.ManyToManyField(related_name='upgrading', to='Main.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='admitted_students',
            field=models.ManyToManyField(related_name='admitted', to='Main.student'),
        ),
    ]
