# Generated by Django 4.2.5 on 2023-09-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_course_confirmed_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_to_upgrade',
        ),
    ]
